"""
Vector Search API — semantic similarity search across alert history.

Uses Qdrant vector database with Ollama embeddings to find similar
historical incidents based on natural-language queries.

Endpoints:
- GET  /api/vectors/alerts/similar  — Semantic search for similar alerts
- GET  /api/vectors/status          — Vector store health + collection stats
- POST /api/vectors/reindex         — Re-index all existing alerts
"""

from __future__ import annotations

from typing import Optional

from fastapi import APIRouter, HTTPException, Query

from app.services.alert_engine import alert_engine
from app.services.ai_service import ai_service
from app.services.vector_store import vector_store

router = APIRouter(prefix="/api/vectors", tags=["vector-search"])


@router.get("/alerts/similar")
async def search_similar_alerts(
    query: str = Query(..., description="Natural language query describing the alert scenario"),
    server: Optional[str] = Query(default=None, description="Optional server filter"),
    metric: Optional[str] = Query(default=None, description="Optional metric filter (cpu, memory, disk, etc.)"),
    severity: Optional[str] = Query(default=None, description="Optional severity filter (critical, warning, info)"),
    top_k: int = Query(default=5, ge=1, le=50, description="Number of results to return"),
    min_score: float = Query(default=0.3, ge=0.0, le=1.0, description="Minimum similarity score threshold"),
):
    """
    Search for alerts semantically similar to the given query text.

    Uses Qdrant vector similarity search with Ollama embeddings.
    Example queries:
    - "connection pool exhausted on database server"
    - "high CPU on web server during deployment"
    - "disk full alert on monitoring node"
    - "memory leak pattern similar to last week"
    """
    results = await vector_store.similarity_search(
        query=query,
        server_filter=server,
        metric_filter=metric,
        severity_filter=severity,
        top_k=top_k,
        score_threshold=min_score,
    )

    return {
        "query": query,
        "filters": {
            "server": server,
            "metric": metric,
            "severity": severity,
        },
        "results": results,
        "total": len(results),
    }


@router.get("/alerts/{alert_id}/similar")
async def find_similar_to_alert(
    alert_id: str,
    top_k: int = Query(default=5, ge=1, le=50),
):
    """
    Find alerts semantically similar to a specific alert by its ID.

    Uses the alert's message + server + metric as the query for
    vector similarity search. Useful for finding related incidents
    that may share the same root cause.
    """
    # Find the alert
    all_alerts = alert_engine.get_all_alerts()
    target = next((a for a in all_alerts if a.id == alert_id), None)
    if not target:
        raise HTTPException(
            status_code=404,
            detail=f"Alert '{alert_id}' not found",
        )

    results = await alert_engine.find_similar_alerts(target, top_k=top_k)

    return {
        "source_alert": {
            "id": target.id,
            "server": target.server,
            "metric": target.metric,
            "severity": target.severity,
            "message": target.message,
        },
        "similar_alerts": results,
        "total": len(results),
    }


@router.get("/status")
async def vector_store_status():
    """Get the vector store health status and collection statistics."""
    available = await vector_store.is_available()
    stats = await vector_store.get_collection_stats()

    return {
        "qdrant_available": available,
        "ollama_available": available,  # Derived from ability to embed
        "collection": stats,
    }


@router.get("/cache-stats")
async def get_cache_statistics():
    """
    Get cache hit rate statistics for the remediation cache.

    Tracks how many remediation requests were served from Qdrant cache
    vs generated by Ollama, with average durations for each tier.

    Returns:
        total_requests, cache_hits, rag_fallbacks, full_analysis,
        cache_hit_rate (%), ollama_savings_seconds, avg durations
    """
    return ai_service.get_cache_stats()


@router.post("/cache-stats/reset")
async def reset_cache_statistics():
    """Reset all cache statistics counters to zero."""
    ai_service.reset_cache_stats()
    return {"message": "Cache statistics reset", "status": "ok"}


@router.post("/reindex")
async def reindex_alerts():
    """
    Re-index all existing alerts into the vector store.

    Useful after restoring from backup or if the vector store was
    cleared. Pre-existing vectors are upserted (overwritten).
    """
    all_alerts = alert_engine.get_all_alerts()
    alert_dicts = [a.model_dump() for a in all_alerts]

    result = await vector_store.reindex_alerts(alert_dicts)

    return {
        "message": "Re-indexing complete",
        "total_alerts": result["total"],
        "indexed": result["success"],
        "failed": result["failed"],
    }
